<?php

/**
 * Created by PhpStorm.
 * User: jiangfan
 * Date: 2017/8/8
 * Time: 上午12:25
 */
namespace app\mjs\model;
use app\mjs\model\Base;

class JsClassifyModel extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

   public function getClassifyList($where=[]){
      return self::where($where)->field('*')->paginate(10);
   }


}